[package]
name = "pros-command-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pros = { version = "0.3.0", path = "../../pros-rs/pros" }
pros-command = { version = "0.1.0", path = ".." }
